// Categories and words for the Impostor game

export interface WordData {
  word: string;
  hint: string; // Hint for the impostor
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  words: WordData[];
  color: string;
}

export const CATEGORIES: Category[] = [
  {
    id: "food",
    name: "Food & Drinks",
    icon: "🍕",
    color: "180 80% 70%",
    words: [
      { word: "Pizza", hint: "Italian dish" },
      { word: "Sushi", hint: "Japanese food" },
      { word: "Burger", hint: "Fast food" },
      { word: "Tacos", hint: "Mexican food" },
      { word: "Ice Cream", hint: "Frozen dessert" },
      { word: "Coffee", hint: "Hot beverage" },
      { word: "Pasta", hint: "Italian noodles" },
      { word: "Chocolate", hint: "Sweet treat" },
      { word: "Steak", hint: "Grilled meat" },
      { word: "Salad", hint: "Healthy greens" },
      { word: "Sandwich", hint: "Bread-based meal" },
      { word: "Smoothie", hint: "Blended drink" },
      { word: "Pancakes", hint: "Breakfast item" },
      { word: "Ramen", hint: "Noodle soup" },
      { word: "Curry", hint: "Spicy dish" },
      { word: "Spaghetti", hint: "Long pasta" },
      { word: "Cheesecake", hint: "Creamy dessert" },
      { word: "Waffles", hint: "Grid-patterned breakfast" },
      { word: "Lasagna", hint: "Layered pasta" },
      { word: "Fried Chicken", hint: "Crispy poultry" },
      { word: "Hot Dog", hint: "Stadium food" },
      { word: "French Fries", hint: "Potato sticks" },
      { word: "Donut", hint: "Ring-shaped pastry" },
      { word: "Brownie", hint: "Chocolate square" },
      { word: "Milkshake", hint: "Creamy drink" },
      { word: "Nachos", hint: "Chips with toppings" },
      { word: "Quesadilla", hint: "Cheese tortilla" },
      { word: "Croissant", hint: "French pastry" },
      { word: "Bagel", hint: "Round bread" },
      { word: "Pretzel", hint: "Twisted snack" },
      { word: "Popcorn", hint: "Movie snack" },
      { word: "Cheese", hint: "Dairy product" },
      { word: "Bacon", hint: "Crispy pork" },
      { word: "Omelette", hint: "Egg dish" },
      { word: "Soup", hint: "Liquid meal" },
      { word: "Burrito", hint: "Wrapped Mexican" },
      { word: "Spring Roll", hint: "Asian appetizer" },
      { word: "Dim Sum", hint: "Chinese dumplings" },
      { word: "Pad Thai", hint: "Thai noodles" },
      { word: "Fish and Chips", hint: "British classic" },
      { word: "Meatballs", hint: "Round meat" },
      { word: "Mac and Cheese", hint: "Cheesy pasta" },
      { word: "Hummus", hint: "Chickpea dip" },
      { word: "Guacamole", hint: "Avocado dip" },
      { word: "Caesar Salad", hint: "Roman lettuce" },
      { word: "Tiramisu", hint: "Coffee dessert" },
      { word: "Panna Cotta", hint: "Italian cream" },
      { word: "Gelato", hint: "Italian ice cream" },
      { word: "Boba Tea", hint: "Bubble drink" },
      { word: "Espresso", hint: "Strong coffee" },
      { word: "Lemonade", hint: "Citrus drink" },
      { word: "Orange Juice", hint: "Morning drink" },
      { word: "Apple Pie", hint: "American dessert" },
      { word: "Banana Split", hint: "Ice cream boat" },
      { word: "Churros", hint: "Fried dough" },
      { word: "Muffin", hint: "Small cake" },
      { word: "Cupcake", hint: "Mini frosted cake" },
      { word: "Cookie", hint: "Sweet biscuit" },
      { word: "Bread", hint: "Baked staple" },
      { word: "Rice", hint: "Asian grain" },
      { word: "Noodles", hint: "Long strands" },
      { word: "Tofu", hint: "Soy protein" },
      { word: "Shrimp", hint: "Seafood" },
      { word: "Lobster", hint: "Luxury seafood" },
      { word: "Crab", hint: "Shellfish" },
      { word: "Oysters", hint: "Raw seafood" },
      { word: "Caviar", hint: "Fish eggs" },
      { word: "Truffle", hint: "Rare fungi" },
      { word: "Foie Gras", hint: "French delicacy" },
      { word: "Paella", hint: "Spanish rice" },
      { word: "Risotto", hint: "Creamy rice" },
      { word: "Gnocchi", hint: "Potato pasta" },
      { word: "Ravioli", hint: "Stuffed pasta" },
      { word: "Cannoli", hint: "Sicilian pastry" },
      { word: "Baklava", hint: "Honey pastry" },
      { word: "Falafel", hint: "Chickpea balls" },
      { word: "Shawarma", hint: "Wrapped meat" },
      { word: "Kebab", hint: "Skewered meat" },
      { word: "Samosa", hint: "Indian snack" },
      { word: "Biryani", hint: "Spiced rice" },
      { word: "Naan", hint: "Indian bread" },
      { word: "Tikka Masala", hint: "Creamy curry" },
      { word: "Pho", hint: "Vietnamese soup" },
      { word: "Bibimbap", hint: "Korean bowl" },
      { word: "Kimchi", hint: "Fermented cabbage" },
      { word: "Tempura", hint: "Fried Japanese" },
      { word: "Teriyaki", hint: "Sweet glaze" },
      { word: "Miso Soup", hint: "Japanese broth" },
      { word: "Edamame", hint: "Green beans" },
      { word: "Sashimi", hint: "Raw fish" },
      { word: "Gyoza", hint: "Japanese dumpling" },
      { word: "Udon", hint: "Thick noodles" },
      { word: "Takoyaki", hint: "Octopus balls" },
      { word: "Okonomiyaki", hint: "Japanese pancake" },
      { word: "Poke Bowl", hint: "Hawaiian dish" },
      { word: "Ceviche", hint: "Raw fish dish" },
      { word: "Empanada", hint: "Filled pastry" },
      { word: "Tamale", hint: "Corn wrapped" },
      { word: "Elote", hint: "Mexican corn" }
    ]
  },
  {
    id: "animals",
    name: "Animals",
    icon: "🐾",
    color: "140 60% 60%",
    words: [
      { word: "Dog", hint: "Pet companion" },
      { word: "Cat", hint: "House pet" },
      { word: "Elephant", hint: "Large mammal" },
      { word: "Lion", hint: "King of jungle" },
      { word: "Dolphin", hint: "Ocean mammal" },
      { word: "Eagle", hint: "Bird of prey" },
      { word: "Snake", hint: "Reptile" },
      { word: "Penguin", hint: "Flightless bird" },
      { word: "Koala", hint: "Australian animal" },
      { word: "Giraffe", hint: "Tall animal" },
      { word: "Monkey", hint: "Primate" },
      { word: "Tiger", hint: "Striped cat" },
      { word: "Bear", hint: "Forest animal" },
      { word: "Rabbit", hint: "Hopping animal" },
      { word: "Horse", hint: "Riding animal" },
      { word: "Zebra", hint: "Striped horse" },
      { word: "Kangaroo", hint: "Jumping marsupial" },
      { word: "Panda", hint: "Black and white" },
      { word: "Wolf", hint: "Wild dog" },
      { word: "Fox", hint: "Clever canine" },
      { word: "Deer", hint: "Forest hoofed" },
      { word: "Owl", hint: "Night bird" },
      { word: "Parrot", hint: "Talking bird" },
      { word: "Flamingo", hint: "Pink bird" },
      { word: "Peacock", hint: "Colorful tail" },
      { word: "Swan", hint: "Elegant bird" },
      { word: "Duck", hint: "Pond bird" },
      { word: "Goose", hint: "Honking bird" },
      { word: "Chicken", hint: "Farm bird" },
      { word: "Turkey", hint: "Holiday bird" },
      { word: "Crocodile", hint: "Water reptile" },
      { word: "Alligator", hint: "Swamp reptile" },
      { word: "Turtle", hint: "Shelled reptile" },
      { word: "Lizard", hint: "Small reptile" },
      { word: "Chameleon", hint: "Color changer" },
      { word: "Iguana", hint: "Large lizard" },
      { word: "Frog", hint: "Hopping amphibian" },
      { word: "Toad", hint: "Warty amphibian" },
      { word: "Shark", hint: "Ocean predator" },
      { word: "Whale", hint: "Giant mammal" },
      { word: "Octopus", hint: "Eight arms" },
      { word: "Jellyfish", hint: "Stinging sea" },
      { word: "Starfish", hint: "Star shaped" },
      { word: "Seahorse", hint: "Horse shaped fish" },
      { word: "Crab", hint: "Sideways walker" },
      { word: "Lobster", hint: "Clawed crustacean" },
      { word: "Shrimp", hint: "Small seafood" },
      { word: "Clam", hint: "Shell creature" },
      { word: "Snail", hint: "Slow creature" },
      { word: "Butterfly", hint: "Winged insect" },
      { word: "Bee", hint: "Honey maker" },
      { word: "Ant", hint: "Tiny insect" },
      { word: "Spider", hint: "Web spinner" },
      { word: "Scorpion", hint: "Stinging arachnid" },
      { word: "Ladybug", hint: "Spotted beetle" },
      { word: "Dragonfly", hint: "Flying insect" },
      { word: "Grasshopper", hint: "Jumping insect" },
      { word: "Mosquito", hint: "Biting insect" },
      { word: "Fly", hint: "Common insect" },
      { word: "Beetle", hint: "Hard shell" },
      { word: "Caterpillar", hint: "Future butterfly" },
      { word: "Moth", hint: "Night butterfly" },
      { word: "Firefly", hint: "Glowing bug" },
      { word: "Cockroach", hint: "Unwanted pest" },
      { word: "Gorilla", hint: "Large ape" },
      { word: "Chimpanzee", hint: "Smart ape" },
      { word: "Orangutan", hint: "Orange ape" },
      { word: "Baboon", hint: "Colorful monkey" },
      { word: "Lemur", hint: "Madagascar primate" },
      { word: "Sloth", hint: "Slow mammal" },
      { word: "Armadillo", hint: "Armored mammal" },
      { word: "Anteater", hint: "Long tongue" },
      { word: "Platypus", hint: "Egg-laying mammal" },
      { word: "Beaver", hint: "Dam builder" },
      { word: "Otter", hint: "Playful swimmer" },
      { word: "Seal", hint: "Ocean mammal" },
      { word: "Walrus", hint: "Tusked mammal" },
      { word: "Polar Bear", hint: "Arctic predator" },
      { word: "Moose", hint: "Large antlers" },
      { word: "Elk", hint: "Forest deer" },
      { word: "Bison", hint: "American buffalo" },
      { word: "Rhino", hint: "Horned mammal" },
      { word: "Hippo", hint: "River horse" },
      { word: "Camel", hint: "Desert animal" },
      { word: "Llama", hint: "South American" },
      { word: "Alpaca", hint: "Fluffy llama" },
      { word: "Goat", hint: "Mountain climber" },
      { word: "Sheep", hint: "Woolly animal" },
      { word: "Pig", hint: "Farm animal" },
      { word: "Cow", hint: "Dairy animal" },
      { word: "Bull", hint: "Male cattle" },
      { word: "Donkey", hint: "Stubborn animal" },
      { word: "Mule", hint: "Horse donkey mix" },
      { word: "Hedgehog", hint: "Spiny mammal" },
      { word: "Porcupine", hint: "Quilled rodent" },
      { word: "Squirrel", hint: "Nut gatherer" },
      { word: "Chipmunk", hint: "Striped rodent" },
      { word: "Hamster", hint: "Pet rodent" },
      { word: "Guinea Pig", hint: "Cute rodent" },
      { word: "Mouse", hint: "Small rodent" },
      { word: "Rat", hint: "City rodent" }
    ]
  },
  {
    id: "movies",
    name: "Movies & TV",
    icon: "🎬",
    color: "280 70% 65%",
    words: [
      { word: "Titanic", hint: "Ship disaster" },
      { word: "Avatar", hint: "Blue aliens" },
      { word: "Friends", hint: "NYC sitcom" },
      { word: "Batman", hint: "Dark superhero" },
      { word: "Frozen", hint: "Ice princess" },
      { word: "Stranger Things", hint: "Upside down" },
      { word: "The Office", hint: "Workplace comedy" },
      { word: "Star Wars", hint: "Space saga" },
      { word: "Harry Potter", hint: "Wizard boy" },
      { word: "Marvel", hint: "Superhero universe" },
      { word: "Game of Thrones", hint: "Fantasy kingdoms" },
      { word: "Inception", hint: "Dream layers" },
      { word: "Matrix", hint: "Red pill" },
      { word: "Breaking Bad", hint: "Chemistry teacher" },
      { word: "Jurassic Park", hint: "Dinosaur theme" },
      { word: "The Lion King", hint: "African prince" },
      { word: "Toy Story", hint: "Living toys" },
      { word: "Finding Nemo", hint: "Lost fish" },
      { word: "Shrek", hint: "Green ogre" },
      { word: "Spider-Man", hint: "Web slinger" },
      { word: "The Godfather", hint: "Mafia family" },
      { word: "Forrest Gump", hint: "Running man" },
      { word: "The Shawshank Redemption", hint: "Prison escape" },
      { word: "Pulp Fiction", hint: "Crime anthology" },
      { word: "Fight Club", hint: "Secret society" },
      { word: "The Dark Knight", hint: "Joker villain" },
      { word: "Interstellar", hint: "Space travel" },
      { word: "Gladiator", hint: "Roman arena" },
      { word: "Braveheart", hint: "Scottish freedom" },
      { word: "Schindler's List", hint: "Holocaust drama" },
      { word: "The Silence of the Lambs", hint: "Cannibal doctor" },
      { word: "Se7en", hint: "Deadly sins" },
      { word: "Memento", hint: "Memory loss" },
      { word: "The Prestige", hint: "Magic rivalry" },
      { word: "Jaws", hint: "Shark attack" },
      { word: "E.T.", hint: "Alien friend" },
      { word: "Back to the Future", hint: "Time car" },
      { word: "Ghostbusters", hint: "Spirit hunters" },
      { word: "Indiana Jones", hint: "Treasure hunter" },
      { word: "Rocky", hint: "Boxing underdog" },
      { word: "The Terminator", hint: "Robot assassin" },
      { word: "Alien", hint: "Space horror" },
      { word: "Die Hard", hint: "Christmas action" },
      { word: "Top Gun", hint: "Fighter pilots" },
      { word: "Mission Impossible", hint: "Spy action" },
      { word: "James Bond", hint: "British spy" },
      { word: "Pirates of the Caribbean", hint: "Jack Sparrow" },
      { word: "Lord of the Rings", hint: "One ring" },
      { word: "The Hobbit", hint: "Short journey" },
      { word: "The Hunger Games", hint: "Survival games" },
      { word: "Twilight", hint: "Vampire romance" },
      { word: "The Notebook", hint: "Love letters" },
      { word: "Pretty Woman", hint: "Rich romance" },
      { word: "Grease", hint: "50s musical" },
      { word: "Dirty Dancing", hint: "Dance romance" },
      { word: "The Wizard of Oz", hint: "Yellow brick" },
      { word: "Mary Poppins", hint: "Magic nanny" },
      { word: "The Sound of Music", hint: "Austrian hills" },
      { word: "Casablanca", hint: "Wartime romance" },
      { word: "Singin' in the Rain", hint: "Rain dance" },
      { word: "The Exorcist", hint: "Possessed girl" },
      { word: "The Shining", hint: "Hotel horror" },
      { word: "Halloween", hint: "Masked killer" },
      { word: "Nightmare on Elm Street", hint: "Dream killer" },
      { word: "Scream", hint: "Ghost face" },
      { word: "The Conjuring", hint: "Paranormal investigation" },
      { word: "It", hint: "Scary clown" },
      { word: "Get Out", hint: "Sunken place" },
      { word: "The Sixth Sense", hint: "Dead people" },
      { word: "Squid Game", hint: "Deadly games" },
      { word: "Money Heist", hint: "Bank robbery" },
      { word: "Peaky Blinders", hint: "British gang" },
      { word: "The Crown", hint: "Royal family" },
      { word: "Wednesday", hint: "Addams daughter" },
      { word: "Bridgerton", hint: "Regency romance" },
      { word: "Euphoria", hint: "Teen drama" },
      { word: "Succession", hint: "Rich family" },
      { word: "Ted Lasso", hint: "Football coach" },
      { word: "The Mandalorian", hint: "Baby Yoda" },
      { word: "WandaVision", hint: "Sitcom reality" },
      { word: "Loki", hint: "God of mischief" },
      { word: "The Witcher", hint: "Monster hunter" },
      { word: "The Boys", hint: "Corrupt heroes" },
      { word: "Lucifer", hint: "Devil detective" },
      { word: "Sherlock", hint: "Modern detective" },
      { word: "Black Mirror", hint: "Tech dystopia" },
      { word: "The Walking Dead", hint: "Zombie survival" },
      { word: "Westworld", hint: "Robot park" },
      { word: "Mindhunter", hint: "Serial killers" },
      { word: "Ozark", hint: "Money laundering" },
      { word: "Narcos", hint: "Drug cartel" },
      { word: "The Simpsons", hint: "Yellow family" },
      { word: "Family Guy", hint: "Talking dog" },
      { word: "South Park", hint: "Colorado kids" },
      { word: "Rick and Morty", hint: "Dimension travel" },
      { word: "SpongeBob", hint: "Sea sponge" },
      { word: "Adventure Time", hint: "Candy kingdom" },
      { word: "Avatar The Last Airbender", hint: "Element bender" },
      { word: "Demon Slayer", hint: "Anime swords" },
      { word: "Attack on Titan", hint: "Giant monsters" }
    ]
  },
  {
    id: "sports",
    name: "Sports",
    icon: "⚽",
    color: "35 90% 60%",
    words: [
      { word: "Soccer", hint: "World's game" },
      { word: "Basketball", hint: "Hoops sport" },
      { word: "Tennis", hint: "Racket sport" },
      { word: "Swimming", hint: "Water sport" },
      { word: "Golf", hint: "Club sport" },
      { word: "Baseball", hint: "American pastime" },
      { word: "Hockey", hint: "Ice sport" },
      { word: "Boxing", hint: "Fighting sport" },
      { word: "Volleyball", hint: "Net sport" },
      { word: "Cricket", hint: "Bat and ball" },
      { word: "Rugby", hint: "Oval ball" },
      { word: "Skiing", hint: "Snow sport" },
      { word: "Surfing", hint: "Wave riding" },
      { word: "Cycling", hint: "Bike sport" },
      { word: "Wrestling", hint: "Grappling sport" },
      { word: "Gymnastics", hint: "Flexibility sport" },
      { word: "Track and Field", hint: "Running events" },
      { word: "Marathon", hint: "Long run" },
      { word: "Triathlon", hint: "Three sports" },
      { word: "Badminton", hint: "Shuttlecock sport" },
      { word: "Table Tennis", hint: "Ping pong" },
      { word: "Bowling", hint: "Pin sport" },
      { word: "Archery", hint: "Arrow sport" },
      { word: "Fencing", hint: "Sword sport" },
      { word: "Karate", hint: "Martial art" },
      { word: "Judo", hint: "Japanese wrestling" },
      { word: "Taekwondo", hint: "Korean martial" },
      { word: "MMA", hint: "Mixed fighting" },
      { word: "Skateboarding", hint: "Board tricks" },
      { word: "Snowboarding", hint: "Snow board" },
      { word: "Figure Skating", hint: "Ice dance" },
      { word: "Speed Skating", hint: "Fast ice" },
      { word: "Bobsled", hint: "Ice toboggan" },
      { word: "Luge", hint: "Ice sled" },
      { word: "Curling", hint: "Ice shuffleboard" },
      { word: "Rock Climbing", hint: "Wall sport" },
      { word: "Diving", hint: "High jump water" },
      { word: "Water Polo", hint: "Pool sport" },
      { word: "Rowing", hint: "Boat racing" },
      { word: "Canoeing", hint: "Paddle sport" },
      { word: "Kayaking", hint: "Small boat" },
      { word: "Sailing", hint: "Wind sport" },
      { word: "Windsurfing", hint: "Board sailing" },
      { word: "Kitesurfing", hint: "Kite water" },
      { word: "Polo", hint: "Horse sport" },
      { word: "Equestrian", hint: "Horse riding" },
      { word: "Horse Racing", hint: "Derby sport" },
      { word: "Motor Racing", hint: "Car sport" },
      { word: "Formula 1", hint: "Fast cars" },
      { word: "NASCAR", hint: "American racing" },
      { word: "MotoGP", hint: "Motorcycle racing" },
      { word: "BMX", hint: "Bike tricks" },
      { word: "Motocross", hint: "Dirt bikes" },
      { word: "Handball", hint: "Indoor throwing" },
      { word: "Lacrosse", hint: "Stick sport" },
      { word: "Field Hockey", hint: "Grass hockey" },
      { word: "American Football", hint: "Touchdown sport" },
      { word: "Australian Football", hint: "AFL sport" },
      { word: "Darts", hint: "Throwing sport" },
      { word: "Snooker", hint: "Cue sport" },
      { word: "Pool", hint: "Billiards" },
      { word: "Chess", hint: "Mind sport" },
      { word: "Poker", hint: "Card game" },
      { word: "Esports", hint: "Video gaming" },
      { word: "Cheerleading", hint: "Spirit sport" },
      { word: "Dance Sport", hint: "Ballroom" },
      { word: "Parkour", hint: "Urban running" },
      { word: "CrossFit", hint: "Intense fitness" },
      { word: "Powerlifting", hint: "Heavy lifting" },
      { word: "Weightlifting", hint: "Olympic lifting" },
      { word: "Bodybuilding", hint: "Muscle sport" },
      { word: "Strongman", hint: "Strength events" },
      { word: "Arm Wrestling", hint: "Hand strength" },
      { word: "Sumo", hint: "Japanese wrestling" },
      { word: "Kickboxing", hint: "Feet and fists" },
      { word: "Muay Thai", hint: "Thai boxing" },
      { word: "Capoeira", hint: "Brazilian dance fight" },
      { word: "Aikido", hint: "Japanese defense" },
      { word: "Kendo", hint: "Sword martial" },
      { word: "Ultimate Frisbee", hint: "Flying disc" },
      { word: "Disc Golf", hint: "Frisbee golf" },
      { word: "Pickleball", hint: "Paddle ball" },
      { word: "Squash", hint: "Wall racket" },
      { word: "Racquetball", hint: "Indoor racket" },
      { word: "Paddle Tennis", hint: "Outdoor racket" },
      { word: "Beach Volleyball", hint: "Sand sport" },
      { word: "Sepak Takraw", hint: "Kick volleyball" },
      { word: "Jai Alai", hint: "Fastest ball" },
      { word: "Hurling", hint: "Irish sport" },
      { word: "Gaelic Football", hint: "Irish football" },
      { word: "Kabaddi", hint: "Tag wrestling" },
      { word: "Netball", hint: "Women basketball" },
      { word: "Softball", hint: "Underhand baseball" },
      { word: "Wiffle Ball", hint: "Backyard baseball" },
      { word: "Dodgeball", hint: "School sport" },
      { word: "Kickball", hint: "Soccer baseball" },
      { word: "Tug of War", hint: "Rope pulling" },
      { word: "Pentathlon", hint: "Five sports" },
      { word: "Decathlon", hint: "Ten events" },
      { word: "Heptathlon", hint: "Seven events" }
    ]
  },
  {
    id: "football",
    name: "Football",
    icon: "⚽",
    color: "120 70% 50%",
    words: [
      { word: "Lionel Messi", hint: "Argentine legend" },
      { word: "Cristiano Ronaldo", hint: "Portuguese star" },
      { word: "Neymar", hint: "Brazilian forward" },
      { word: "Kylian Mbappé", hint: "French speedster" },
      { word: "Erling Haaland", hint: "Norwegian striker" },
      { word: "Real Madrid", hint: "Spanish giants" },
      { word: "Barcelona", hint: "Catalan club" },
      { word: "Manchester United", hint: "Red Devils" },
      { word: "Manchester City", hint: "Citizens" },
      { word: "Liverpool", hint: "Reds from Anfield" },
      { word: "Bayern Munich", hint: "German champions" },
      { word: "PSG", hint: "Paris club" },
      { word: "Juventus", hint: "Italian champions" },
      { word: "AC Milan", hint: "Rossoneri" },
      { word: "Inter Milan", hint: "Nerazzurri" },
      { word: "Chelsea", hint: "London Blues" },
      { word: "Arsenal", hint: "Gunners" },
      { word: "Tottenham", hint: "Spurs" },
      { word: "Borussia Dortmund", hint: "Yellow Wall" },
      { word: "Atletico Madrid", hint: "Madrid rojiblancos" },
      { word: "World Cup", hint: "Global tournament" },
      { word: "Champions League", hint: "Top club competition" },
      { word: "Premier League", hint: "English league" },
      { word: "La Liga", hint: "Spanish league" },
      { word: "Serie A", hint: "Italian league" },
      { word: "Bundesliga", hint: "German league" },
      { word: "Ligue 1", hint: "French league" },
      { word: "Euro Cup", hint: "European nations" },
      { word: "Copa America", hint: "South American cup" },
      { word: "Afrika Cup", hint: "African nations" },
      { word: "Penalty Kick", hint: "Spot kick" },
      { word: "Free Kick", hint: "Set piece" },
      { word: "Corner Kick", hint: "Flag kick" },
      { word: "Offside", hint: "Position rule" },
      { word: "Hat Trick", hint: "Three goals" },
      { word: "Red Card", hint: "Ejection card" },
      { word: "Yellow Card", hint: "Warning card" },
      { word: "VAR", hint: "Video review" },
      { word: "Goalkeeper", hint: "Shot stopper" },
      { word: "Striker", hint: "Goal scorer" },
      { word: "Midfielder", hint: "Center player" },
      { word: "Defender", hint: "Back line" },
      { word: "Captain", hint: "Team leader" },
      { word: "Header", hint: "Head goal" },
      { word: "Volley", hint: "Air kick" },
      { word: "Bicycle Kick", hint: "Overhead kick" },
      { word: "Dribbling", hint: "Ball control" },
      { word: "Tackle", hint: "Ball steal" },
      { word: "Assist", hint: "Goal pass" },
      { word: "Clean Sheet", hint: "No goals allowed" },
      { word: "Own Goal", hint: "Self score" },
      { word: "Extra Time", hint: "Added minutes" },
      { word: "Penalty Shootout", hint: "Spot kick decider" },
      { word: "Golden Goal", hint: "Sudden death" },
      { word: "Substitute", hint: "Player change" },
      { word: "Formation", hint: "Team shape" },
      { word: "4-4-2", hint: "Classic formation" },
      { word: "4-3-3", hint: "Attack formation" },
      { word: "Tiki-Taka", hint: "Spanish style" },
      { word: "Counter Attack", hint: "Fast break" },
      { word: "Pressing", hint: "High pressure" },
      { word: "Zidane", hint: "French legend" },
      { word: "Ronaldinho", hint: "Brazilian magician" },
      { word: "Beckham", hint: "Bend it like" },
      { word: "Pele", hint: "Brazilian king" },
      { word: "Maradona", hint: "Hand of God" },
      { word: "Cruyff", hint: "Dutch master" },
      { word: "Maldini", hint: "Italian defender" },
      { word: "Buffon", hint: "Italian keeper" },
      { word: "Iniesta", hint: "Spanish maestro" },
      { word: "Xavi", hint: "Passing master" },
      { word: "Pirlo", hint: "Deep playmaker" },
      { word: "Ibrahimovic", hint: "Swedish giant" },
      { word: "Lewandowski", hint: "Polish striker" },
      { word: "Benzema", hint: "French forward" },
      { word: "Modric", hint: "Croatian midfield" },
      { word: "De Bruyne", hint: "Belgian playmaker" },
      { word: "Salah", hint: "Egyptian King" },
      { word: "Kane", hint: "English captain" },
      { word: "Son Heung-min", hint: "Korean star" },
      { word: "Vinicius Jr", hint: "Brazilian winger" },
      { word: "Bellingham", hint: "English talent" },
      { word: "Casemiro", hint: "Brazilian anchor" },
      { word: "Van Dijk", hint: "Dutch wall" },
      { word: "Alisson", hint: "Brazilian keeper" },
      { word: "Courtois", hint: "Belgian keeper" },
      { word: "Neuer", hint: "Sweeper keeper" },
      { word: "Camp Nou", hint: "Barcelona home" },
      { word: "Santiago Bernabeu", hint: "Madrid home" },
      { word: "Old Trafford", hint: "Theatre of Dreams" },
      { word: "Anfield", hint: "Liverpool home" },
      { word: "Wembley", hint: "English stadium" },
      { word: "San Siro", hint: "Milan stadium" },
      { word: "Maracana", hint: "Brazilian stadium" },
      { word: "Allianz Arena", hint: "Bayern home" },
      { word: "Emirates Stadium", hint: "Arsenal home" },
      { word: "Stamford Bridge", hint: "Chelsea home" },
      { word: "Signal Iduna Park", hint: "Dortmund home" },
      { word: "El Clasico", hint: "Spain derby" },
      { word: "Manchester Derby", hint: "City rivalry" }
    ]
  },
  {
    id: "places",
    name: "Places",
    icon: "🗺️",
    color: "200 70% 55%",
    words: [
      { word: "Paris", hint: "French capital" },
      { word: "Beach", hint: "Sandy shore" },
      { word: "Mountain", hint: "High peak" },
      { word: "Library", hint: "Book place" },
      { word: "Museum", hint: "Art exhibits" },
      { word: "Hospital", hint: "Medical facility" },
      { word: "Airport", hint: "Flight hub" },
      { word: "Restaurant", hint: "Dining place" },
      { word: "School", hint: "Learning place" },
      { word: "Mall", hint: "Shopping center" },
      { word: "Zoo", hint: "Animal park" },
      { word: "Church", hint: "Worship place" },
      { word: "Casino", hint: "Gambling place" },
      { word: "Stadium", hint: "Sports venue" },
      { word: "Cinema", hint: "Movie theater" },
      { word: "New York", hint: "Big Apple" },
      { word: "London", hint: "British capital" },
      { word: "Tokyo", hint: "Japanese capital" },
      { word: "Rome", hint: "Eternal city" },
      { word: "Dubai", hint: "Desert city" },
      { word: "Sydney", hint: "Opera house city" },
      { word: "Los Angeles", hint: "Hollywood city" },
      { word: "Las Vegas", hint: "Sin city" },
      { word: "Miami", hint: "Beach city" },
      { word: "Barcelona", hint: "Gaudi city" },
      { word: "Amsterdam", hint: "Canal city" },
      { word: "Berlin", hint: "German capital" },
      { word: "Moscow", hint: "Russian capital" },
      { word: "Beijing", hint: "Chinese capital" },
      { word: "Hong Kong", hint: "Asian hub" },
      { word: "Singapore", hint: "Island city" },
      { word: "Bangkok", hint: "Thai capital" },
      { word: "Seoul", hint: "Korean capital" },
      { word: "Mumbai", hint: "Bollywood city" },
      { word: "Cairo", hint: "Pyramid city" },
      { word: "Istanbul", hint: "Two continents" },
      { word: "Athens", hint: "Ancient city" },
      { word: "Vienna", hint: "Music city" },
      { word: "Prague", hint: "Czech capital" },
      { word: "Venice", hint: "Water city" },
      { word: "Florence", hint: "Renaissance city" },
      { word: "Lisbon", hint: "Portuguese capital" },
      { word: "Madrid", hint: "Spanish capital" },
      { word: "Copenhagen", hint: "Danish capital" },
      { word: "Stockholm", hint: "Swedish capital" },
      { word: "Oslo", hint: "Norwegian capital" },
      { word: "Helsinki", hint: "Finnish capital" },
      { word: "Reykjavik", hint: "Icelandic capital" },
      { word: "Dublin", hint: "Irish capital" },
      { word: "Edinburgh", hint: "Scottish city" },
      { word: "Eiffel Tower", hint: "Paris landmark" },
      { word: "Statue of Liberty", hint: "NYC landmark" },
      { word: "Big Ben", hint: "London clock" },
      { word: "Colosseum", hint: "Roman arena" },
      { word: "Pyramids", hint: "Egyptian wonders" },
      { word: "Great Wall", hint: "Chinese wonder" },
      { word: "Taj Mahal", hint: "Indian monument" },
      { word: "Machu Picchu", hint: "Inca ruins" },
      { word: "Grand Canyon", hint: "American gorge" },
      { word: "Niagara Falls", hint: "Water border" },
      { word: "Mount Everest", hint: "Highest peak" },
      { word: "Amazon Rainforest", hint: "Green lungs" },
      { word: "Sahara Desert", hint: "African sand" },
      { word: "Antarctica", hint: "Frozen continent" },
      { word: "Hawaii", hint: "Island paradise" },
      { word: "Caribbean", hint: "Island region" },
      { word: "Mediterranean", hint: "Warm sea" },
      { word: "Alps", hint: "European mountains" },
      { word: "Himalayas", hint: "Asian mountains" },
      { word: "Rockies", hint: "American mountains" },
      { word: "Andes", hint: "South American peaks" },
      { word: "Great Barrier Reef", hint: "Coral wonder" },
      { word: "Victoria Falls", hint: "African waterfall" },
      { word: "Yellowstone", hint: "American park" },
      { word: "Yosemite", hint: "California park" },
      { word: "Serengeti", hint: "African safari" },
      { word: "Galápagos", hint: "Darwin islands" },
      { word: "Maldives", hint: "Island nation" },
      { word: "Bali", hint: "Indonesian island" },
      { word: "Santorini", hint: "Greek island" },
      { word: "Ibiza", hint: "Party island" },
      { word: "Phuket", hint: "Thai island" },
      { word: "Fiji", hint: "Pacific islands" },
      { word: "Cancun", hint: "Mexican beach" },
      { word: "Bora Bora", hint: "Tahitian paradise" },
      { word: "Capri", hint: "Italian island" },
      { word: "Mykonos", hint: "Greek party island" },
      { word: "Seychelles", hint: "Indian Ocean" },
      { word: "Mauritius", hint: "Island resort" },
      { word: "Zanzibar", hint: "African island" },
      { word: "Madagascar", hint: "Lemur island" },
      { word: "Iceland", hint: "Fire and ice" },
      { word: "Greenland", hint: "Icy island" },
      { word: "New Zealand", hint: "Middle Earth" },
      { word: "Australia", hint: "Down under" },
      { word: "Canada", hint: "North country" },
      { word: "Brazil", hint: "Carnival country" },
      { word: "Argentina", hint: "Tango country" },
      { word: "Mexico", hint: "Southern neighbor" },
      { word: "Japan", hint: "Land of rising sun" }
    ]
  },
  {
    id: "jobs",
    name: "Jobs",
    icon: "💼",
    color: "330 65% 60%",
    words: [
      { word: "Doctor", hint: "Medical professional" },
      { word: "Teacher", hint: "Educator" },
      { word: "Chef", hint: "Food preparer" },
      { word: "Pilot", hint: "Aircraft operator" },
      { word: "Artist", hint: "Creative person" },
      { word: "Lawyer", hint: "Legal expert" },
      { word: "Engineer", hint: "Problem solver" },
      { word: "Firefighter", hint: "Emergency responder" },
      { word: "Actor", hint: "Performer" },
      { word: "Scientist", hint: "Researcher" },
      { word: "Nurse", hint: "Patient care" },
      { word: "Mechanic", hint: "Vehicle fixer" },
      { word: "Writer", hint: "Word creator" },
      { word: "Police Officer", hint: "Law enforcer" },
      { word: "Designer", hint: "Visual creator" },
      { word: "Dentist", hint: "Tooth doctor" },
      { word: "Veterinarian", hint: "Animal doctor" },
      { word: "Pharmacist", hint: "Medicine expert" },
      { word: "Surgeon", hint: "Operating doctor" },
      { word: "Psychologist", hint: "Mind expert" },
      { word: "Architect", hint: "Building designer" },
      { word: "Accountant", hint: "Number cruncher" },
      { word: "Banker", hint: "Money handler" },
      { word: "Journalist", hint: "News reporter" },
      { word: "Photographer", hint: "Image capturer" },
      { word: "Musician", hint: "Sound maker" },
      { word: "Dancer", hint: "Movement artist" },
      { word: "Director", hint: "Film leader" },
      { word: "Producer", hint: "Content creator" },
      { word: "Comedian", hint: "Funny person" },
      { word: "Model", hint: "Fashion person" },
      { word: "Athlete", hint: "Sports person" },
      { word: "Coach", hint: "Team trainer" },
      { word: "Referee", hint: "Game official" },
      { word: "Lifeguard", hint: "Pool watcher" },
      { word: "Personal Trainer", hint: "Fitness guide" },
      { word: "Nutritionist", hint: "Diet expert" },
      { word: "Therapist", hint: "Healing helper" },
      { word: "Counselor", hint: "Advice giver" },
      { word: "Social Worker", hint: "Community helper" },
      { word: "Paramedic", hint: "Emergency medic" },
      { word: "EMT", hint: "First responder" },
      { word: "Detective", hint: "Crime solver" },
      { word: "Security Guard", hint: "Protection person" },
      { word: "Soldier", hint: "Military person" },
      { word: "Sailor", hint: "Navy person" },
      { word: "Air Force Pilot", hint: "Military flyer" },
      { word: "Astronaut", hint: "Space traveler" },
      { word: "Scientist", hint: "Lab researcher" },
      { word: "Biologist", hint: "Life scientist" },
      { word: "Chemist", hint: "Chemical expert" },
      { word: "Physicist", hint: "Physics expert" },
      { word: "Mathematician", hint: "Number expert" },
      { word: "Data Scientist", hint: "Data analyst" },
      { word: "Software Developer", hint: "Code writer" },
      { word: "Web Developer", hint: "Website maker" },
      { word: "App Developer", hint: "Mobile coder" },
      { word: "Game Developer", hint: "Game maker" },
      { word: "IT Support", hint: "Tech helper" },
      { word: "Network Admin", hint: "System manager" },
      { word: "Cybersecurity", hint: "Digital protector" },
      { word: "UX Designer", hint: "User experience" },
      { word: "Graphic Designer", hint: "Visual artist" },
      { word: "Interior Designer", hint: "Room decorator" },
      { word: "Fashion Designer", hint: "Clothing creator" },
      { word: "Hairdresser", hint: "Hair stylist" },
      { word: "Makeup Artist", hint: "Beauty expert" },
      { word: "Tattoo Artist", hint: "Ink artist" },
      { word: "Florist", hint: "Flower arranger" },
      { word: "Baker", hint: "Bread maker" },
      { word: "Butcher", hint: "Meat cutter" },
      { word: "Bartender", hint: "Drink mixer" },
      { word: "Waiter", hint: "Food server" },
      { word: "Barista", hint: "Coffee maker" },
      { word: "Hotel Manager", hint: "Hospitality boss" },
      { word: "Tour Guide", hint: "Travel helper" },
      { word: "Flight Attendant", hint: "Cabin crew" },
      { word: "Bus Driver", hint: "Transit operator" },
      { word: "Taxi Driver", hint: "Ride provider" },
      { word: "Truck Driver", hint: "Hauler" },
      { word: "Train Conductor", hint: "Rail operator" },
      { word: "Ship Captain", hint: "Vessel commander" },
      { word: "Construction Worker", hint: "Building laborer" },
      { word: "Electrician", hint: "Wire expert" },
      { word: "Plumber", hint: "Pipe fixer" },
      { word: "Carpenter", hint: "Wood worker" },
      { word: "Painter", hint: "Wall colorist" },
      { word: "Roofer", hint: "Top fixer" },
      { word: "Welder", hint: "Metal joiner" },
      { word: "Farmer", hint: "Crop grower" },
      { word: "Rancher", hint: "Animal raiser" },
      { word: "Fisherman", hint: "Fish catcher" },
      { word: "Gardener", hint: "Plant tender" },
      { word: "Landscaper", hint: "Yard designer" },
      { word: "Real Estate Agent", hint: "Property seller" },
      { word: "Insurance Agent", hint: "Policy seller" },
      { word: "Financial Advisor", hint: "Money guide" },
      { word: "CEO", hint: "Company leader" },
      { word: "Manager", hint: "Team leader" },
      { word: "Entrepreneur", hint: "Business starter" }
    ]
  },
  {
    id: "objects",
    name: "Objects",
    icon: "📦",
    color: "45 80% 55%",
    words: [
      { word: "Phone", hint: "Communication device" },
      { word: "Guitar", hint: "String instrument" },
      { word: "Clock", hint: "Time keeper" },
      { word: "Mirror", hint: "Reflection surface" },
      { word: "Umbrella", hint: "Rain protector" },
      { word: "Camera", hint: "Photo taker" },
      { word: "Book", hint: "Reading material" },
      { word: "Lamp", hint: "Light source" },
      { word: "Key", hint: "Lock opener" },
      { word: "Glasses", hint: "Vision aid" },
      { word: "Wallet", hint: "Money holder" },
      { word: "Backpack", hint: "Carrying bag" },
      { word: "Scissors", hint: "Cutting tool" },
      { word: "Candle", hint: "Wax light" },
      { word: "Pillow", hint: "Head rest" },
      { word: "Television", hint: "Screen display" },
      { word: "Computer", hint: "Digital device" },
      { word: "Laptop", hint: "Portable computer" },
      { word: "Tablet", hint: "Touch screen" },
      { word: "Headphones", hint: "Audio device" },
      { word: "Speaker", hint: "Sound output" },
      { word: "Microphone", hint: "Voice recorder" },
      { word: "Keyboard", hint: "Typing device" },
      { word: "Mouse", hint: "Click device" },
      { word: "Printer", hint: "Paper output" },
      { word: "Scanner", hint: "Image capture" },
      { word: "Router", hint: "Internet device" },
      { word: "Charger", hint: "Power source" },
      { word: "Battery", hint: "Energy storage" },
      { word: "USB Drive", hint: "Data storage" },
      { word: "Hard Drive", hint: "Memory storage" },
      { word: "Monitor", hint: "Display screen" },
      { word: "Remote Control", hint: "Wireless controller" },
      { word: "Watch", hint: "Wrist time" },
      { word: "Ring", hint: "Finger jewelry" },
      { word: "Necklace", hint: "Neck jewelry" },
      { word: "Bracelet", hint: "Wrist jewelry" },
      { word: "Earrings", hint: "Ear jewelry" },
      { word: "Sunglasses", hint: "Eye protection" },
      { word: "Hat", hint: "Head cover" },
      { word: "Scarf", hint: "Neck wrap" },
      { word: "Gloves", hint: "Hand cover" },
      { word: "Belt", hint: "Waist strap" },
      { word: "Tie", hint: "Neck formal" },
      { word: "Socks", hint: "Foot cover" },
      { word: "Shoes", hint: "Footwear" },
      { word: "Boots", hint: "Tall shoes" },
      { word: "Sandals", hint: "Open shoes" },
      { word: "Slippers", hint: "Home shoes" },
      { word: "Jacket", hint: "Outer layer" },
      { word: "Coat", hint: "Winter wear" },
      { word: "Sweater", hint: "Warm top" },
      { word: "T-Shirt", hint: "Casual top" },
      { word: "Jeans", hint: "Denim pants" },
      { word: "Shorts", hint: "Short pants" },
      { word: "Dress", hint: "One piece" },
      { word: "Skirt", hint: "Bottom garment" },
      { word: "Suit", hint: "Formal wear" },
      { word: "Pajamas", hint: "Sleep wear" },
      { word: "Swimsuit", hint: "Beach wear" },
      { word: "Towel", hint: "Drying cloth" },
      { word: "Blanket", hint: "Bed cover" },
      { word: "Sheet", hint: "Bed linen" },
      { word: "Curtain", hint: "Window cover" },
      { word: "Carpet", hint: "Floor cover" },
      { word: "Rug", hint: "Small carpet" },
      { word: "Chair", hint: "Sitting furniture" },
      { word: "Table", hint: "Surface furniture" },
      { word: "Desk", hint: "Work surface" },
      { word: "Sofa", hint: "Living seat" },
      { word: "Bed", hint: "Sleep furniture" },
      { word: "Dresser", hint: "Clothes storage" },
      { word: "Cabinet", hint: "Storage unit" },
      { word: "Shelf", hint: "Display surface" },
      { word: "Drawer", hint: "Pull storage" },
      { word: "Door", hint: "Entry barrier" },
      { word: "Window", hint: "Glass opening" },
      { word: "Stairs", hint: "Level connector" },
      { word: "Elevator", hint: "Vertical transport" },
      { word: "Fan", hint: "Air mover" },
      { word: "Air Conditioner", hint: "Cool maker" },
      { word: "Heater", hint: "Warm maker" },
      { word: "Refrigerator", hint: "Food cooler" },
      { word: "Microwave", hint: "Quick heater" },
      { word: "Oven", hint: "Baking appliance" },
      { word: "Stove", hint: "Cooking surface" },
      { word: "Toaster", hint: "Bread warmer" },
      { word: "Blender", hint: "Mixing machine" },
      { word: "Coffee Maker", hint: "Brew machine" },
      { word: "Dishwasher", hint: "Plate cleaner" },
      { word: "Washing Machine", hint: "Clothes cleaner" },
      { word: "Dryer", hint: "Clothes dryer" },
      { word: "Vacuum", hint: "Floor cleaner" },
      { word: "Iron", hint: "Clothes presser" },
      { word: "Broom", hint: "Floor sweeper" },
      { word: "Mop", hint: "Wet cleaner" },
      { word: "Bucket", hint: "Water holder" },
      { word: "Trash Can", hint: "Waste holder" },
      { word: "Soap", hint: "Cleaning agent" },
      { word: "Shampoo", hint: "Hair cleaner" }
    ]
  },
  {
    id: "actions",
    name: "Actions",
    icon: "🎭",
    color: "0 70% 65%",
    words: [
      { word: "Dancing", hint: "Moving to music" },
      { word: "Swimming", hint: "Water movement" },
      { word: "Cooking", hint: "Food preparation" },
      { word: "Reading", hint: "Book activity" },
      { word: "Sleeping", hint: "Rest time" },
      { word: "Running", hint: "Fast movement" },
      { word: "Singing", hint: "Voice music" },
      { word: "Painting", hint: "Art creation" },
      { word: "Driving", hint: "Vehicle operation" },
      { word: "Shopping", hint: "Buying things" },
      { word: "Studying", hint: "Learning activity" },
      { word: "Traveling", hint: "Going places" },
      { word: "Gaming", hint: "Playing video" },
      { word: "Fishing", hint: "Catching fish" },
      { word: "Climbing", hint: "Going up" },
      { word: "Writing", hint: "Creating text" },
      { word: "Typing", hint: "Keyboard use" },
      { word: "Walking", hint: "Slow movement" },
      { word: "Jogging", hint: "Light running" },
      { word: "Hiking", hint: "Trail walking" },
      { word: "Camping", hint: "Outdoor staying" },
      { word: "Skiing", hint: "Snow sliding" },
      { word: "Surfing", hint: "Wave riding" },
      { word: "Skating", hint: "Wheel rolling" },
      { word: "Cycling", hint: "Bike riding" },
      { word: "Jumping", hint: "Air movement" },
      { word: "Throwing", hint: "Object launching" },
      { word: "Catching", hint: "Object grabbing" },
      { word: "Kicking", hint: "Foot action" },
      { word: "Punching", hint: "Fist action" },
      { word: "Hugging", hint: "Embrace action" },
      { word: "Kissing", hint: "Lip action" },
      { word: "Waving", hint: "Hand greeting" },
      { word: "Clapping", hint: "Hand applause" },
      { word: "Snapping", hint: "Finger action" },
      { word: "Whistling", hint: "Mouth sound" },
      { word: "Laughing", hint: "Happy sound" },
      { word: "Crying", hint: "Sad expression" },
      { word: "Smiling", hint: "Happy face" },
      { word: "Frowning", hint: "Sad face" },
      { word: "Thinking", hint: "Mental activity" },
      { word: "Dreaming", hint: "Sleep fantasy" },
      { word: "Meditating", hint: "Mindful rest" },
      { word: "Praying", hint: "Spiritual act" },
      { word: "Stretching", hint: "Body extension" },
      { word: "Exercising", hint: "Physical activity" },
      { word: "Lifting", hint: "Weight raising" },
      { word: "Pushing", hint: "Force application" },
      { word: "Pulling", hint: "Force attraction" },
      { word: "Carrying", hint: "Object transport" },
      { word: "Dropping", hint: "Object release" },
      { word: "Breaking", hint: "Object destruction" },
      { word: "Building", hint: "Construction activity" },
      { word: "Fixing", hint: "Repair action" },
      { word: "Cleaning", hint: "Tidying up" },
      { word: "Washing", hint: "Water cleaning" },
      { word: "Drying", hint: "Moisture removal" },
      { word: "Folding", hint: "Creasing action" },
      { word: "Ironing", hint: "Wrinkle removal" },
      { word: "Sewing", hint: "Needle work" },
      { word: "Knitting", hint: "Yarn work" },
      { word: "Cutting", hint: "Dividing action" },
      { word: "Chopping", hint: "Food cutting" },
      { word: "Mixing", hint: "Combining action" },
      { word: "Stirring", hint: "Circular mixing" },
      { word: "Baking", hint: "Oven cooking" },
      { word: "Frying", hint: "Pan cooking" },
      { word: "Boiling", hint: "Hot water" },
      { word: "Grilling", hint: "Fire cooking" },
      { word: "Eating", hint: "Food consumption" },
      { word: "Drinking", hint: "Liquid consumption" },
      { word: "Chewing", hint: "Food processing" },
      { word: "Swallowing", hint: "Ingesting food" },
      { word: "Tasting", hint: "Flavor testing" },
      { word: "Smelling", hint: "Odor detection" },
      { word: "Listening", hint: "Sound attention" },
      { word: "Watching", hint: "Visual attention" },
      { word: "Looking", hint: "Eye direction" },
      { word: "Searching", hint: "Finding activity" },
      { word: "Finding", hint: "Discovery action" },
      { word: "Hiding", hint: "Concealment action" },
      { word: "Seeking", hint: "Search game" },
      { word: "Chasing", hint: "Pursuit action" },
      { word: "Escaping", hint: "Fleeing action" },
      { word: "Fighting", hint: "Combat action" },
      { word: "Defending", hint: "Protection action" },
      { word: "Attacking", hint: "Offense action" },
      { word: "Winning", hint: "Victory achievement" },
      { word: "Losing", hint: "Defeat experience" },
      { word: "Celebrating", hint: "Joy expression" },
      { word: "Mourning", hint: "Grief expression" },
      { word: "Waiting", hint: "Time passing" },
      { word: "Hurrying", hint: "Fast action" },
      { word: "Relaxing", hint: "Calm state" },
      { word: "Working", hint: "Job activity" },
      { word: "Playing", hint: "Fun activity" },
      { word: "Resting", hint: "Recovery time" },
      { word: "Talking", hint: "Verbal communication" },
      { word: "Whispering", hint: "Quiet speaking" },
      { word: "Shouting", hint: "Loud speaking" }
    ]
  },
  {
    id: "nature",
    name: "Nature",
    icon: "🌿",
    color: "150 60% 50%",
    words: [
      { word: "Ocean", hint: "Large water body" },
      { word: "Forest", hint: "Tree area" },
      { word: "Mountain", hint: "High land" },
      { word: "River", hint: "Flowing water" },
      { word: "Lake", hint: "Still water" },
      { word: "Waterfall", hint: "Falling water" },
      { word: "Desert", hint: "Sandy dry" },
      { word: "Jungle", hint: "Dense forest" },
      { word: "Volcano", hint: "Erupting mountain" },
      { word: "Island", hint: "Water surrounded" },
      { word: "Cave", hint: "Rock hollow" },
      { word: "Canyon", hint: "Deep gorge" },
      { word: "Valley", hint: "Low land" },
      { word: "Cliff", hint: "Steep rock" },
      { word: "Glacier", hint: "Ice mass" },
      { word: "Rainbow", hint: "Color arc" },
      { word: "Lightning", hint: "Electric flash" },
      { word: "Thunder", hint: "Storm sound" },
      { word: "Tornado", hint: "Spinning wind" },
      { word: "Hurricane", hint: "Tropical storm" },
      { word: "Earthquake", hint: "Ground shaking" },
      { word: "Tsunami", hint: "Giant wave" },
      { word: "Blizzard", hint: "Snow storm" },
      { word: "Drought", hint: "No rain" },
      { word: "Flood", hint: "Water overflow" },
      { word: "Sunrise", hint: "Day beginning" },
      { word: "Sunset", hint: "Day ending" },
      { word: "Moon", hint: "Night light" },
      { word: "Stars", hint: "Night dots" },
      { word: "Sun", hint: "Day star" },
      { word: "Cloud", hint: "Sky puff" },
      { word: "Rain", hint: "Water drops" },
      { word: "Snow", hint: "White precipitation" },
      { word: "Hail", hint: "Ice balls" },
      { word: "Fog", hint: "Ground cloud" },
      { word: "Mist", hint: "Light fog" },
      { word: "Dew", hint: "Morning water" },
      { word: "Frost", hint: "Cold ice" },
      { word: "Wind", hint: "Air movement" },
      { word: "Breeze", hint: "Light wind" },
      { word: "Storm", hint: "Weather event" },
      { word: "Tree", hint: "Tall plant" },
      { word: "Flower", hint: "Colorful plant" },
      { word: "Grass", hint: "Green ground" },
      { word: "Bush", hint: "Small tree" },
      { word: "Fern", hint: "Leafy plant" },
      { word: "Moss", hint: "Rock plant" },
      { word: "Mushroom", hint: "Fungi growth" },
      { word: "Cactus", hint: "Desert plant" },
      { word: "Palm Tree", hint: "Tropical tree" },
      { word: "Pine Tree", hint: "Needle tree" },
      { word: "Oak Tree", hint: "Acorn tree" },
      { word: "Bamboo", hint: "Fast plant" },
      { word: "Rose", hint: "Thorny flower" },
      { word: "Tulip", hint: "Dutch flower" },
      { word: "Sunflower", hint: "Yellow flower" },
      { word: "Daisy", hint: "White flower" },
      { word: "Lily", hint: "Elegant flower" },
      { word: "Orchid", hint: "Exotic flower" },
      { word: "Lavender", hint: "Purple herb" },
      { word: "Coral", hint: "Ocean structure" },
      { word: "Seaweed", hint: "Ocean plant" },
      { word: "Kelp", hint: "Large seaweed" },
      { word: "Sand", hint: "Beach grain" },
      { word: "Rock", hint: "Hard mineral" },
      { word: "Stone", hint: "Small rock" },
      { word: "Boulder", hint: "Large rock" },
      { word: "Pebble", hint: "Tiny rock" },
      { word: "Crystal", hint: "Clear mineral" },
      { word: "Diamond", hint: "Precious stone" },
      { word: "Gold", hint: "Yellow metal" },
      { word: "Silver", hint: "Gray metal" },
      { word: "Copper", hint: "Brown metal" },
      { word: "Coal", hint: "Black fuel" },
      { word: "Oil", hint: "Liquid fuel" },
      { word: "Gas", hint: "Air fuel" },
      { word: "Soil", hint: "Ground dirt" },
      { word: "Mud", hint: "Wet dirt" },
      { word: "Clay", hint: "Pottery material" },
      { word: "Lava", hint: "Hot rock" },
      { word: "Ash", hint: "Burnt remains" },
      { word: "Smoke", hint: "Fire cloud" },
      { word: "Fire", hint: "Burning flame" },
      { word: "Ice", hint: "Frozen water" },
      { word: "Steam", hint: "Hot vapor" },
      { word: "Pond", hint: "Small lake" },
      { word: "Stream", hint: "Small river" },
      { word: "Brook", hint: "Tiny stream" },
      { word: "Spring", hint: "Water source" },
      { word: "Swamp", hint: "Wet land" },
      { word: "Marsh", hint: "Grassy swamp" },
      { word: "Meadow", hint: "Grass field" },
      { word: "Prairie", hint: "Flat grass" },
      { word: "Tundra", hint: "Cold plain" },
      { word: "Savanna", hint: "Grass plain" },
      { word: "Reef", hint: "Ocean formation" },
      { word: "Geyser", hint: "Hot spring" },
      { word: "Aurora", hint: "Sky lights" },
      { word: "Eclipse", hint: "Sun moon" },
      { word: "Comet", hint: "Space ice" }
    ]
  },
  {
    id: "technology",
    name: "Technology",
    icon: "💻",
    color: "220 70% 60%",
    words: [
      { word: "Smartphone", hint: "Pocket computer" },
      { word: "Laptop", hint: "Portable PC" },
      { word: "Tablet", hint: "Touch device" },
      { word: "Desktop", hint: "Office computer" },
      { word: "Server", hint: "Network computer" },
      { word: "Cloud", hint: "Online storage" },
      { word: "Internet", hint: "Global network" },
      { word: "WiFi", hint: "Wireless connection" },
      { word: "Bluetooth", hint: "Short range" },
      { word: "GPS", hint: "Location system" },
      { word: "App", hint: "Mobile program" },
      { word: "Software", hint: "Computer program" },
      { word: "Hardware", hint: "Physical parts" },
      { word: "Website", hint: "Online page" },
      { word: "Browser", hint: "Web viewer" },
      { word: "Email", hint: "Electronic mail" },
      { word: "Social Media", hint: "Online sharing" },
      { word: "Streaming", hint: "Online video" },
      { word: "Podcast", hint: "Audio show" },
      { word: "Blog", hint: "Online journal" },
      { word: "Artificial Intelligence", hint: "Smart machines" },
      { word: "Robot", hint: "Automated machine" },
      { word: "Drone", hint: "Flying robot" },
      { word: "Virtual Reality", hint: "Immersive tech" },
      { word: "Augmented Reality", hint: "Overlay tech" },
      { word: "3D Printing", hint: "Object making" },
      { word: "Cryptocurrency", hint: "Digital money" },
      { word: "Bitcoin", hint: "First crypto" },
      { word: "Blockchain", hint: "Secure ledger" },
      { word: "NFT", hint: "Digital art" },
      { word: "Firewall", hint: "Security barrier" },
      { word: "Antivirus", hint: "Malware protection" },
      { word: "Password", hint: "Access code" },
      { word: "Encryption", hint: "Data scramble" },
      { word: "Hacker", hint: "System breaker" },
      { word: "Virus", hint: "Bad program" },
      { word: "Malware", hint: "Harmful software" },
      { word: "Download", hint: "Get file" },
      { word: "Upload", hint: "Send file" },
      { word: "Update", hint: "New version" },
      { word: "Bug", hint: "Code error" },
      { word: "Code", hint: "Programming language" },
      { word: "Algorithm", hint: "Step process" },
      { word: "Database", hint: "Data storage" },
      { word: "Backup", hint: "Data copy" },
      { word: "Router", hint: "Network device" },
      { word: "Modem", hint: "Internet device" },
      { word: "Processor", hint: "Computer brain" },
      { word: "RAM", hint: "Fast memory" },
      { word: "SSD", hint: "Fast storage" },
      { word: "GPU", hint: "Graphics chip" },
      { word: "USB", hint: "Universal port" },
      { word: "HDMI", hint: "Video cable" },
      { word: "Webcam", hint: "Video camera" },
      { word: "Microphone", hint: "Audio input" },
      { word: "Speaker", hint: "Audio output" },
      { word: "Keyboard", hint: "Typing device" },
      { word: "Mouse", hint: "Pointing device" },
      { word: "Monitor", hint: "Display screen" },
      { word: "Printer", hint: "Paper output" },
      { word: "Scanner", hint: "Document input" },
      { word: "Smart Home", hint: "Connected house" },
      { word: "Smart Watch", hint: "Wrist computer" },
      { word: "Fitness Tracker", hint: "Health monitor" },
      { word: "Electric Car", hint: "Battery vehicle" },
      { word: "Self-Driving Car", hint: "Autonomous vehicle" },
      { word: "Solar Panel", hint: "Sun energy" },
      { word: "Wind Turbine", hint: "Wind energy" },
      { word: "Battery", hint: "Power storage" },
      { word: "Charger", hint: "Power supply" },
      { word: "Satellite", hint: "Space device" },
      { word: "Space Station", hint: "Orbital lab" },
      { word: "Rocket", hint: "Space vehicle" },
      { word: "Telescope", hint: "Space viewer" },
      { word: "Microscope", hint: "Small viewer" },
      { word: "MRI", hint: "Body scanner" },
      { word: "X-Ray", hint: "Bone image" },
      { word: "Ultrasound", hint: "Sound image" },
      { word: "Laser", hint: "Light beam" },
      { word: "LED", hint: "Light diode" },
      { word: "OLED", hint: "Organic light" },
      { word: "LCD", hint: "Liquid display" },
      { word: "Touchscreen", hint: "Touch display" },
      { word: "E-Reader", hint: "Digital book" },
      { word: "Game Console", hint: "Gaming device" },
      { word: "Controller", hint: "Game input" },
      { word: "VR Headset", hint: "Virtual viewer" },
      { word: "Smart Speaker", hint: "Voice assistant" },
      { word: "Thermostat", hint: "Temperature control" },
      { word: "Security Camera", hint: "Surveillance device" },
      { word: "Doorbell Camera", hint: "Entry monitor" },
      { word: "Smart Lock", hint: "Digital lock" },
      { word: "Wireless Earbuds", hint: "Cordless audio" },
      { word: "Power Bank", hint: "Portable charger" },
      { word: "USB-C", hint: "New connector" },
      { word: "5G", hint: "Fast network" },
      { word: "Fiber Optic", hint: "Light internet" },
      { word: "QR Code", hint: "Square barcode" },
      { word: "Biometrics", hint: "Body ID" },
      { word: "Face ID", hint: "Face recognition" }
    ]
  }
];

export const getRandomWord = (categoryId: string): WordData => {
  const category = CATEGORIES.find(c => c.id === categoryId);
  if (!category) return { word: "Unknown", hint: "No hint available" };
  const randomIndex = Math.floor(Math.random() * category.words.length);
  return category.words[randomIndex];
};

export const getCategoryById = (id: string): Category | undefined => {
  return CATEGORIES.find(c => c.id === id);
};
